################################################
# Copyright (c) 2022 by Keneth Polledo Baynas  # 
# https://www.facebook.com/dtsiken             #
# itskenethb@gmail.com                         #
################################################

#THIS SCRIPT IS USED TO TRACK PHONE NUMBER LOCATION
#ALSO THE INFORMATION ABOUT IT
#DO NOT USE TO ANY MALICIOUS PURPOSES!
#WE ALL KNOW THAT WE DON'T WANT TO GO IN JAIL AND OUR LOCATION AND INFORMATION TO BE LEAKED SO PLEASE USE IT FOR AWARENESS TO KNOW THAT THIS IS REALLY EXISTED TO OUR LOVE ONES AND THE WE ARE CLOSE TO!

#TUTORIALS!!!

#ATTENTION:TO CHANGE THE NUMBER THAT YOU WANT TO TRACK!
#GO TO THE ANOTHER .py FILE IN THE SAME DIRECTORY AND CHANGE IT
# HE NAME OF FILE IS test.py
#FIRST INPUT THE COUNTRY CODE EXAMPLE: +639 AND THEN THE NUMBER
#THIS IS THE FORMAT IN test.py Below
#number = "+639<YOUR NUMBER YOU WANT TO TRACK ANY NUMBER NOT ONLY IN PHILIPPINES WILL ALSO WORK>"
#FIND AND HIT SAVE OR PRESS CTRL + S TO SAVE THE CHANGES

#ADDITIONAL REQUIREMENTS!!!
#DIRECTIONS:
#FIRST YOU NEED TO INSTALL THE PYTHON LIBRARY IN THE TERMINAL BECAUSE IT WILL NOT WORK AS WE EXPECTING
#FIRST LIBRARY THAT NEED TO BE DOWNLOADED IS phonenumbers
#TYPE pip install phonenumbers AND PRESS ENTER
#AFTER THAT NEXT LIBRARY IS opencage
#IN THE TERMINAL AGAIN TYPE pip install opencage(FOR LATITUDE AND LONGITUDE)
#AFTER DOWNLOADING THE opencage LIBRARY GO TO THEIR WEBSITE AND CREATE FREE ACCOUNT LINK IS BELOW AND COPY PASTE THE API KEY!
#LAST LIBRARY THAT WE NEED IS folium(FOR THE MAP VIEW THAT WILL STORED TO AN HTML FILE)

#AFTER ALL DOWNLOADED JUST IMPORT IT BEFORE START CODING LIKE BELOW!
from tkinter.tix import PopupMenu
#FIRST LIBRARY THAT WE DOWNLOADED
import phonenumbers
#SPECIFY THE PYTHON FILE THAT CONTAINS INPUTED DATA OF PHONE NUMBER
from test import number
#SECOND LIBRARY THAT WE DOWNLOADED 
import opencage
#THIRD LIBRARY THAT WE DOWNLOADED
import folium

#API Key Generated by Creating Free Account
#https://opencagedata.com
Key = 'c4a659cac46a4d7b9211b45ff59c5cfc'

#Imports the phonenumber Python Library
from phonenumbers import geocoder

#Here Will Show the Location Country of the Phone Number
pepnumber = phonenumbers.parse(number, "CH")
location = geocoder.description_for_number(pepnumber, "en")
print(location)
 
#Here Will Show the Name of the Service Provider of The Number
from phonenumbers import carrier
service_pro = phonenumbers.parse(number)
print(carrier.name_for_number(service_pro, "en"))

#SpecIfy the Opencage Library and import it
from opencage.geocoder import OpenCageGeocode

#Specify the API Key that Declares to a Variable Name Key
geocoder = OpenCageGeocode(Key)
query = str(location)

#Showing the Results and Locates Geographical Location
results = geocoder.geocode(query)
lat = results[0]['geometry']['lat']
lng = results[0]['geometry']['lng']
print(lat,lng)

#To Show the Location in the Map for Detailed View
myMap = folium.Map(location=[lat, lng], zoom_start=9)
folium.Marker([lat, lng], popup=location).add_to(myMap)

#Creates a HTML File in The Same Directory
#This will store the Geographical Location and can be Opened in Web Browsers
myMap.save("save.html")